### ISSUE TITLE
List on https://internetcomputer.org/tooling/

### ISSUE THREAD

**Issue by domwoe** [dfinity/idl2json#9]
Please provide a PR to https://github.com/dfinity/portal to make it easier for developers to find this useful tool :)

The tool would need to be added to `src/components/Common/toolingItems.ts`.

Thank you!

**Comment by bitdivine** [comment]
Done: https://github.com/dfinity/portal/pull/866

**Comment by bitdivine** [comment]
Keeping this open until the PR is merged....
